# Generated by Django 2.1.1 on 2018-11-02 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=40)),
                ('question', models.TextField()),
                ('mcq', models.BooleanField(default=True)),
                ('positive_score', models.IntegerField(default=0)),
                ('negative_score', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('options', models.TextField(default='{}')),
                ('correct_answer', models.IntegerField(default=0)),
                ('explaination', models.TextField(default='No explaination')),
            ],
        ),
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(blank=True, default='', max_length=40)),
                ('category', models.CharField(default='General', max_length=100)),
                ('poster', models.CharField(blank=True, max_length=2000)),
                ('quote', models.CharField(blank=True, max_length=100)),
                ('stars', models.TextField(default='0,0,0,0,0')),
                ('prizes', models.TextField(default='Not Declared', max_length=5000)),
                ('about', models.TextField(default='No details.', max_length=5000)),
                ('announcements', models.TextField(default='No Announcements', max_length=5000)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('portal_duration', models.IntegerField(default=0)),
                ('can_change_answer', models.BooleanField(default=False)),
                ('individual_timing', models.BooleanField(default=True)),
                ('rated', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
                ('ready', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TriviaResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('answers', models.TextField(default='{}')),
                ('positive_score', models.IntegerField(default=0)),
                ('negative_score', models.IntegerField(default=0)),
                ('stars', models.IntegerField(default=0)),
                ('trivia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia.Trivia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='trivia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia.Trivia'),
        ),
    ]
