# Generated by Django 2.1.1 on 2018-09-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0002_trivia_portal_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='trivia',
            name='live',
            field=models.BooleanField(default=False),
        ),
    ]
