# Generated by Django 2.1.1 on 2018-09-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0003_trivia_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='trivia',
            name='password',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='trivia',
            name='negative_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trivia',
            name='positive_score',
            field=models.IntegerField(default=0),
        ),
    ]
