# Generated by Django 2.1.1 on 2018-09-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0004_auto_20180915_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='trivia',
            name='poster',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='trivia',
            name='quote',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
