# Generated by Django 2.1.1 on 2018-09-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0005_auto_20180915_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trivia',
            name='poster',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='trivia',
            name='quote',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
