# Generated by Django 2.1.1 on 2018-09-19 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trivia', '0007_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriviaResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_elapsed', models.IntegerField(default=0)),
                ('answers', models.TextField(default='')),
                ('score', models.IntegerField(default=0)),
                ('trivia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia.Trivia')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(default=''),
        ),
    ]
