# Generated by Django 2.1.1 on 2018-09-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0008_auto_20180919_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='trivia',
            name='can_change_answer',
            field=models.BooleanField(default=False),
        ),
    ]
