# Generated by Django 2.1.1 on 2018-10-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0009_trivia_can_change_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.TextField(default='{}'),
            preserve_default=False,
        ),
    ]
