# Generated by Django 2.1.1 on 2018-10-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0010_auto_20181008_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.TextField(default='\\{\\}'),
        ),
    ]
