# Generated by Django 2.1.1 on 2018-10-08 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0013_auto_20181008_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trivia',
            old_name='portal',
            new_name='individual_timings',
        ),
    ]
