# Generated by Django 2.1.1 on 2018-10-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0014_auto_20181008_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trivia',
            old_name='individual_timings',
            new_name='individual_timing',
        ),
        migrations.RemoveField(
            model_name='trivia',
            name='per_problem_duration',
        ),
        migrations.AddField(
            model_name='trivia',
            name='question_timing',
            field=models.BooleanField(default=True),
        ),
    ]
