# Generated by Django 2.1.1 on 2018-10-08 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0015_auto_20181008_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trivia',
            name='can_navigate',
        ),
    ]
