# Generated by Django 2.1.1 on 2018-10-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0016_remove_trivia_can_navigate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triviaresult',
            name='time_elapsed',
        ),
        migrations.AddField(
            model_name='triviaresult',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
