# Generated by Django 2.1.1 on 2018-10-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0017_auto_20181008_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='triviaresult',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
