# Generated by Django 2.1.1 on 2018-10-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0019_trivia_per_questions_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trivia',
            name='per_questions_duration',
        ),
        migrations.AddField(
            model_name='question',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
