# Generated by Django 2.1.1 on 2018-10-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0020_auto_20181009_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trivia',
            name='question_timing',
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='triviaresult',
            name='answers',
            field=models.TextField(default='{}'),
        ),
    ]
