# Generated by Django 2.1.1 on 2018-10-14 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0022_auto_20181013_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triviaresult',
            name='negative_score',
        ),
    ]
