# Generated by Django 2.1.1 on 2018-10-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0023_remove_triviaresult_negative_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='triviaresult',
            name='negative_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='triviaresult',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
