# Generated by Django 2.1.1 on 2018-10-15 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0024_auto_20181014_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triviaresult',
            old_name='username',
            new_name='user',
        ),
    ]
