# Generated by Django 2.1.1 on 2018-10-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0027_auto_20181018_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='trivia',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
