# Generated by Django 2.1.1 on 2018-10-19 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0029_auto_20181018_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trivia',
            old_name='prize',
            new_name='prizes',
        ),
    ]
