# Generated by Django 2.1.1 on 2018-10-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0031_remove_trivia_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default=' ', max_length=40),
        ),
    ]
