# Generated by Django 2.1.1 on 2018-10-25 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0032_question_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='title',
            new_name='q_title',
        ),
    ]
