# Generated by Django 2.1.1 on 2018-10-25 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0033_auto_20181025_0528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='q_title',
            new_name='title',
        ),
    ]
