# Generated by Django 2.1.1 on 2018-10-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0035_trivia_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='trivia',
            name='rating',
            field=models.TextField(default='{1:0, 2:0, 3:0, 4:0, 5:0}'),
        ),
    ]
