# Generated by Django 2.1.1 on 2018-10-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0036_trivia_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trivia',
            name='rating',
            field=models.TextField(default='[0,0,0,0,0]'),
        ),
    ]
