# Generated by Django 2.1.1 on 2018-10-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0038_auto_20181027_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triviaresult',
            name='feedback',
            field=models.IntegerField(default=0),
        ),
    ]
