# Generated by Django 2.1.1 on 2018-10-27 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0039_auto_20181027_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triviaresult',
            old_name='feedback',
            new_name='stars',
        ),
    ]
