# Generated by Django 2.1.1 on 2018-10-27 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0040_auto_20181027_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trivia',
            old_name='rating',
            new_name='stars',
        ),
    ]
