# Generated by Django 2.1.1 on 2018-10-27 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0042_triviapracticeresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triviapracticeresult',
            name='trivia',
        ),
        migrations.RemoveField(
            model_name='triviapracticeresult',
            name='user',
        ),
        migrations.DeleteModel(
            name='TriviaPracticeResult',
        ),
    ]
