# Generated by Django 2.1.1 on 2018-10-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0043_auto_20181027_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='triviaresult',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
