# Generated by Django 2.1.1 on 2018-10-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0044_triviaresult_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='trivia',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
