# Generated by Django 2.1.1 on 2018-09-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userdetails_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='last_active',
            field=models.DateTimeField(null=True),
        ),
    ]
