# Generated by Django 2.1.1 on 2018-09-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userdetails_last_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
